version: "3.8"
services:
  api:
    image: "suryawarior44/rest-training:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=training_mk2
      - PORT=:8000
      - JWT_SECRET=secret
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=training_mk2
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
