name: Deploy to EC2
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 by using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/app
          git pull origin master
          docker stop myApp
          docker rm myApp
          cd program
          docker build -t my-app:latest .
          docker run -d -e "HTTP_PORT=:80" -p 80:80 --name myApp my-app:latest